project_id = "tend-mobile"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "to.every.tend://auth-callback"
additional_redirect_urls = ["to.every.tend://auth-callback"]
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false
