export const CLI_COMMANDS = [
  "help",
  "state [--feed inbox]",
  "setup:detect-monologue",
  "context:bind --thread <Chronicle thread id> [--replace]",
  "context:publish --thread <Chronicle thread id> --context-file <path>",
  "context:status",
  "context:for-feed --feed <id>",
  "agent:presence --agent claude --session <id> [--label <text>]",
  "feed:create --brief <plain-English brief> [--thread <current Codex thread id>]",
  "feed:bind --feed <id> (--thread <Codex thread id> | --agent claude [--replace])",
  "feed:drain-agent --feed <id> --agent <codex|claude>",
  "feed:archive --feed <id>",
  "feed:heartbeat:propose --feed <id> --cadence <plain-English cadence>",
  "feed:heartbeat:installed --feed <id> --automation <id>",
  "source:add --feed <id> --brief <plain-English source recipe>",
  "source:remove --feed <id> --source <id>",
  "source:record-run --feed <id> --source <id> --snapshots <json> --judgments <json> --checkpoint <json> [--work <recollection-work-id>] [--context-use <json> | --context-use-file <path>]",
  "sweep:record-batch --feed <id> --runs <json-array> [--work <recollection-work-id>] [--context <mind-update-id>]",
  "sweep:rejudge --feed <id> --feedback <id> --ordered-cards <json-array> --removed-cards <json-array>",
  "source:import-json-file --feed <id> --source <id> --path <local-json-file>",
  "source:import-file --feed <id> --source <id> --path <local-text-or-jsonl-file>",
  "card:upsert --feed <id> (--card <json> | --card-file <path>)",
  "routine:upsert --feed <id> --group <json>",
  "routine:approve --feed <id> --group <id>",
  "card:dismiss --feed <id> --card <id>",
  "card:cleanup-source --feed <id> --card <id>",
  "card:undo-cleanup-source --feed <id> --card <id>",
  "card:return-to-review --feed <id> --card <id>",
  "work:list --feed <id> --thread <id> [--cross-feed]",
  "work:claim --feed <id> --thread <id> [--cross-feed] [--session <id>]",
  "work:assign --feed <id> --work <id> --agent <codex|claude>",
  "work:release --feed <id> --work <id> --token <token> [--session <id>]",
  "work:cancel --feed <id> --work <id> [--reason <text>]",
  "work:edit --feed <id> --work <id> --instruction <text>",
  "work:complete --feed <id> --work <id> --token <token> --result <json>",
  "action:verify --feed <id> --work <id> --token <token> [--mailbox <authenticated-gmail-email>]",
  "work:fail --feed <id> --work <id> --token <token> --error <text>",
  "work:block --feed <id> --work <id> --token <token> --error <text>",
  "work:reconcile-approved --feed <id> --work <id> --token <token> --result <json>",
  "work:retry --feed <id> --work <id>",
  "policy:apply --feed <id> (--content <markdown> | --content-file <path>) --reason <text> [--source micro_learning]",
  "policy:revert --feed <id> --revision <id>",
  "revision:propose --feed <anchor-id> --target <json> --instruction <text> (--content <markdown> | --content-file <path>) [--source compound]",
  "revision:update --proposal <id> (--content <markdown> | --content-file <path>)",
  "revision:reject --proposal <id>",
  "learning:request --feed <id>",
  "global-policy:update --content <markdown>",
  "global-prompt:update --prompt <allowlisted-name.md> --content <markdown>",
  "proposal:create --feed <id> --title <text> --brief <text> --instruction <text>",
  "feedback:record --feed <id> --title <text> --detail <text> [--source-thread <Codex thread id>]",
  "feedback:list",
  "feedback:resolve --feedback <id> --resolution <text>",
  "runtime:where",
  "inspect --feed <id>",
  "demo:seed [--feed inbox]",
  "demo:clear [--feed inbox]",
] as const;

export const INTERNAL_CLI_COMMANDS = [
  "legacy:import-attention-card --feed <id> --path <attention-batch-json> --card-id <id>",
  "legacy:import-inbox-card --feed inbox --path <inbox-sweep-brief-json> --card-id <id> [--mailbox <received-at-email>]",
] as const;

export function cliCommandName(command: string): string {
  return command.split(" ")[0] ?? command;
}

export function cliCommandUsage(commandName: string): string | undefined {
  return [...CLI_COMMANDS, ...INTERNAL_CLI_COMMANDS].find((command) => cliCommandName(command) === commandName);
}
